token = "" #necessary, modify it for your security!
content_length_limit = 51200 #B, the max size of a clipboard content

[client.connect]
url = "http://example.com:4533/" #necessary
type = "polling" # specify connect mode, "polling" or "persist"
interval = 1000 #ms, the interval time in *polling* mode
timeout = 10000 #ms, the timeout of http client in *polling* mode if 0, uclipboard will create a default (wait forever) client
upload_timeout = 300 #s, the timeout of uploading file operation


[client.adapter]
type = "" #necessary, specify the adapter method, e.g. "xc" for xclip, "wc" for win-clip, "wl" for wl-clipboard, "pbm" for macos pbman, 
X_selection = "clipboard" # select the clipboard which you want to copy/paste in xc adapter

[server]
timer_interval = 60 #seconds, the interval of rubbish cleaner timer
access_log = false #print access log

[server.store]
db_path = "./uclipboard.db" 
tmp_path = "./tmp/" #temporary uploaded file path
default_file_life = 300 #seconds, temporary uploaded file life
max_clipboard_record_number = 0 # the max number of clipboard records, if 0, uclipboard don't remove outdated records

[server.api]
pull_size = 5 # the number of clipboard records to pull per request
history_page_size = 20 # the number of clipboard records per page in history api
port = 4533 
cache_max_age = 2592000 #seconds, 30 days in default the max age of cache
ping_interval = 5000 #ms, the interval time of server ping client operation in websocket api