token = "" # Required. Set your own token for security.
content_length_limit = 51200 # B. Maximum clipboard content size in bytes.

[client.connect]
url = "http://example.com:4533/" # Required. Server URL.
type = "polling" # Connection mode: "polling" or "persist". Only X11/xsel does not support "persist".
interval = 1000 # ms. Polling interval in "polling" mode.

timeout = 10000 # ms. Connection timeout. If set to 0, waits indefinitely in "polling" mode.
# For "persist" mode, consider lowering this value (e.g., 6000) for faster read timeouts.
# In "persist" mode, this should be greater than server.api.ping_interval to avoid unexpected connection closures.

upload_timeout = 300 # s. Timeout for file uploads.

[client.adapter]
type = "" # Required. Adapter type: "xc" (xclip), "wc" (win-clip), "wl" (wl-clipboard), "pbm" (macOS pbman), etc.
X_selection = "clipboard" # Clipboard selection for "xc" adapter.

[server]
timer_interval = 60 # s. Interval for cleanup timer.
access_log = false # Print access logs.

[server.store]
db_path = "./uclipboard.db"
tmp_path = "./tmp/" # Temporary file upload path.
default_file_life = 300 # s. Lifetime of temporary uploaded files.
max_clipboard_record_number = 0 # Maximum clipboard records. 0 means unlimited.

[server.api]
pull_size = 5 # Number of clipboard records per pull request.
history_page_size = 20 # Number of records per page in history API.
port = 4533
cache_max_age = 2592000 # s. Cache max age (default: 30 days).
ping_interval = 5000 # ms. Interval for server ping to client in WebSocket API.
